spring:
  application:
    name: "${APPLICATION_NAME:booking-management}"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8081
  servlet:
    context-path: "/${APPLICATION_PREFIX:nexus/v1}"
  error.include-stacktrace: never

log:
  file:
    path: "${LOG_PATH:/tmp/logs}"

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "healthcheck"

logging:
  level:
    feign.client: DEBUG

api:
  secret: "{API_SECRET:Dsp#2025@v1Pr0v!@}"